# -*- coding: utf-8 -*-
"""Movie Recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJV77N068QOz9pHfdil6vdzh87Qv01MY

**WORK FLOW**
--------------
DATA -> DATA Pre-Processing -> Feature extraction -> User input -> Cosine Similarity -> List of Movies
"""

import pandas as pd
 import numpy as np
 import difflib # words similarity 'Spelling Mistake'
 from sklearn.feature_extraction.text import TfidfVectorizer # text to feature(numerical) vectors
 from sklearn.metrics.pairwise import cosine_similarity

"""**Data Collection and Pre-Processing**"""

# loading the csv data file of movie.csv
movie = pd.read_csv('movies.csv')

# show fist 5 rows and columns
movie.head()

# How many rows and columns in the data set
movie.shape

# checking missing value of data st\
movie.isnull().sum()

# selecting feature recommendation
selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

# checking missig value of selected features
movie[selected_features].isnull().sum()

# replacing null values
for feature in selected_features:
    movie[feature] = movie[feature].fillna('')

# checking missig value of selected features
movie[selected_features].isnull().sum()

# combining all features
combined_features = movie['genres']+' '+movie['keywords']+''+movie['tagline']+' '+movie['cast']+' '+movie['director']
print(combined_features)

# convert text data to numerical data
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)

feature_vectors.shape

"""**Cosine Similarity**"""

# checking similarityscore
similarity = cosine_similarity(feature_vectors)
print(similarity)

similarity.shape

movie_title = movie['title']

for title in movie_title:
    print(title)

# Movie enter by the user
movie_name = input('Enter your favorite movie name : ')

# find the close match of the movie given by user
close_match = difflib.get_close_matches(movie_name, movie['title'])

# Display the close matches vertically
for title in close_match:
    index = title[0]
    print(title)

chosen_movie_title = close_match[0]
print(chosen_movie_title)

# find index of the movie
if close_match:
    chosen_movie_title = close_match[0]
    # Filter the DataFrame for the chosen movie title and get its 'index' column value
    index_movie = movie[movie.title == chosen_movie_title]['index'].iloc[0]
    print(index_movie)

similarity_score = list(enumerate(similarity[index_movie]))
for score in similarity_score:
    print(score)

# sorting similarity score
sorted_similarity_score = sorted(similarity_score, key = lambda x:x[1], reverse = True)
for score in sorted_similarity_score:
    print(score)

# print the name of similar movie

print('Movie Suggested for you:\n')

i = 1

for movie_tuple in sorted_similarity_score:
  index = movie_tuple[0]
  title_from_index = movie_title.loc[index]
  if (i<30):
    print(f"{i}. {title_from_index}")
    i+=1

"""Movie Recommendation System"""

movie_name = input('Enter your favourite movie name:')

titles_for_matching = movie_title.tolist()

close_match = difflib.get_close_matches(movie_name, titles_for_matching)

chosen_movie_title = close_match[0]

index_movie = movie_title[movie_title == chosen_movie_title].index[0]

similarity_score = list(enumerate(similarity[index_movie]))

sorted_similarity_score = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('movie for you:\n')

i = 1

for movie_tuple in sorted_similarity_score:
  index = movie_tuple[0]
  # Access the title from the movie_title Series
  title_from_index = movie_title.loc[index]
  if (i<30):
    print(f"{i}. {title_from_index}")
    i+=1